name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Install Dependencies
      run: |
        go version
        go get github.com/gorilla/mux

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
