name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.3
    
    - name: Install Dependencies
      run: |
        go version
        go get -u github.com/gorilla/mux

    - name: Build
      run: go build ./bs/cmd

    - name: Test
      run: go test -v ./bs/cmd

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./bs/cmd/supermarket_dockerfile
          push: true
          tags: erikturner/supermarket:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
